---
- name: Verify
  hosts: all
  become: true
  vars:
    github_user: "aelsabbahy"
    github_repo: "goss"
    goss_version: "latest"
    goss_arch: "{{ goss_arch_map[ansible_architecture] | default(ansible_architecture) }}"
    goss_dst: "/usr/bin/goss"
    goss_url: "https://github.com/{{ github_user }}/{{ github_repo }}/releases/download/{{ goss_version }}/goss-linux-{{ goss_arch }}"
    goss_test_directory: "/tmp"
    goss_format: "tap"
    goss_arch_map:
      i386: "386"
      x86_64: "amd64"
      aarch64: "arm64"
      armv7l: "armv7"
      armv6l: "armv6"
  tasks:
    - name: Include defaults vars
      include_vars:
        dir: "../../defaults"
        extensions: ["yml", "yaml"]

    - name: Include vars
      include_vars:
        dir: "../../vars"
        extensions: ["yml", "yaml"]

    - name: Ensure dependencies are installed
      pip:
        name: github3.py
      register: _progress_status
      until: _progress_status is succeeded
      delay: 5
      retries: 5

    - name: Get latest Goss release
      block:
        - name: Get latest release
          community.general.github_release:
            user: "{{ github_user }}"
            repo: "{{ github_repo }}"
            token: "{{ lookup('env', 'GHA_TOKEN') }}"
            action: latest_release
          register: _latest_release
          until: _latest_release is succeeded
          delay: 5
          retries: 5

        - name: "Set version tag to {{ _latest_release.tag }}"
          set_fact:
            goss_version: "{{ _latest_release.tag }}"
      when: goss_version == "latest"
      run_once: true

    - name: Download and install Goss
      get_url:
        url: "{{ goss_url }}"
        dest: "{{ goss_dst }}"
        checksum: "sha256:{{ goss_url }}.sha256"
        mode: "0755"
        headers:
          Authorization: "Bearer {{ lookup('env', 'GHA_TOKEN') }}"
      register: _progress_status
      until: _progress_status is succeeded
      delay: 5
      retries: 5

    - name: Copy Goss tests to remote
      template:
        src: "{{ item }}"
        dest: "{{ goss_test_directory }}/{{ item | basename }}"
        mode: "0644"
      with_fileglob:
        - "{{ lookup('env', 'MOLECULE_VERIFIER_TEST_DIRECTORY') }}/*.yml"

    - name: Register test files
      shell: "ls {{ goss_test_directory }}/*.yml"
      changed_when: false
      register: test_files

    - name: Execute Goss tests
      environment:
        PATH: "/opt/rh/rh-git218/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      command: "{{ goss_dst }} -g {{ item }} validate -f {{ goss_format }}"
      changed_when: false
      register: test_results
      with_items: "{{ test_files.stdout_lines }}"
      ignore_errors: true

    - name: Display details about the results
      debug:
        msg: "{{ item.stdout_lines }}"
      with_items: "{{ test_results.results }}"

    - name: Fail when tests fail
      fail:
        msg: "Goss failed to validate"
      when: item.rc != 0
      with_items: "{{ test_results.results }}"
